apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app-role"
        vault.hashicorp.com/agent-inject-secret-db-credentials: "secret/data/db-credentials"
        vault.hashicorp.com/agent-inject-template-db-credentials: |
          {{- with secret "secret/data/db-credentials" -}}
          export POSTGRES_USER="{{ .Data.data.username }}"
          export POSTGRES_PASSWORD="{{ .Data.data.password }}"
          {{- end -}}
    spec:
      securityContext:
        fsGroup: 999
      serviceAccountName: voting-app
      containers:
      - image: postgres:15-alpine
        name: postgres
        command: ["/bin/sh", "-c"]
        args: ["source /vault/secrets/db-credentials && docker-entrypoint.sh postgres"]
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data-pvc

