apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      serviceAccountName: db-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 70
        runAsGroup: 70
        fsGroup: 70
        fsGroupChangePolicy: "OnRootMismatch"
        seccompProfile:
          type: RuntimeDefault
      containers:
      - image: postgres:15.6-alpine
        name: postgres
        command: ["/bin/sh", "-c"]
        args: ["docker-entrypoint.sh postgres"]
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata4
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
        envFrom:
        - secretRef:
            name: db-secret
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 70
          readOnlyRootFilesystem: false
          capabilities:
            drop: ["ALL"]

