apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      serviceAccountName: vote-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - image: patracoder/examplevotingapp_vote:v1.0
        name: vote
        command: ["/bin/sh", "-c"]
        args: ["gunicorn app:app -b 0.0.0.0:8080 --log-file - --access-logfile - --workers 2 --keep-alive 0"]
        envFrom:
        - secretRef:
            name: db-secret
        - secretRef:
            name: redis-secret
        ports:
        - containerPort: 8080
          name: vote
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        volumeMounts:
        - mountPath: /tmp
          name: tmp-dir
      volumes:
      - name: tmp-dir
        emptyDir: {}